# Generated by Django 6.0.2 on 2026-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AlterModelOptions(
            name='alunos',
            options={'verbose_name_plural': 'Alunos'},
        ),
    ]
