# Generated by Django 6.0.2 on 2026-02-22 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_turma_alter_alunos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
    ]
